//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2BProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupons
    {
        public int Coupon_id { get; set; }
        public string Coupon_Code { get; set; }
        public decimal Discount { get; set; }
        public bool IsActive { get; set; }
        public int User_id { get; set; }
        public int Product_id { get; set; }
        public System.DateTime Start_date { get; set; }
        public System.DateTime End_date { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Users Users { get; set; }
    }
}
